[package]
name = "hal-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "*"
quote = "*"
samv71-pac = { path = "../../../../samv71-pac" }
syn = { version = "*", features = ["extra-traits"] }
